[package]
name = "common"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde = {version="*", features= ["derive"]}
bytemuck.workspace = true
